package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AdAuditoria generated by hbm2java
 */
public class AdAuditoria  implements java.io.Serializable {


     private Integer coAuditoria;
     private AdUsuario adUsuario;
     private int coSistema;
     private String nbAccion;
     private String deDescripcion;
     private Date feAuditoria;

    public AdAuditoria() {
    }

    public AdAuditoria(AdUsuario adUsuario, int coSistema, String nbAccion, String deDescripcion, Date feAuditoria) {
       this.adUsuario = adUsuario;
       this.coSistema = coSistema;
       this.nbAccion = nbAccion;
       this.deDescripcion = deDescripcion;
       this.feAuditoria = feAuditoria;
    }
   
    public Integer getCoAuditoria() {
        return this.coAuditoria;
    }
    
    public void setCoAuditoria(Integer coAuditoria) {
        this.coAuditoria = coAuditoria;
    }
    public AdUsuario getAdUsuario() {
        return this.adUsuario;
    }
    
    public void setAdUsuario(AdUsuario adUsuario) {
        this.adUsuario = adUsuario;
    }
    public int getCoSistema() {
        return this.coSistema;
    }
    
    public void setCoSistema(int coSistema) {
        this.coSistema = coSistema;
    }
    public String getNbAccion() {
        return this.nbAccion;
    }
    
    public void setNbAccion(String nbAccion) {
        this.nbAccion = nbAccion;
    }
    public String getDeDescripcion() {
        return this.deDescripcion;
    }
    
    public void setDeDescripcion(String deDescripcion) {
        this.deDescripcion = deDescripcion;
    }
    public Date getFeAuditoria() {
        return this.feAuditoria;
    }
    
    public void setFeAuditoria(Date feAuditoria) {
        this.feAuditoria = feAuditoria;
    }




}


