package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * AdCabeceraEmpresa generated by hbm2java
 */
public class AdCabeceraEmpresa  implements java.io.Serializable {


     private Integer coCabeceraEmpresa;
     private String nbCabeceraEmpresa;
     private String nbTituloCabecera;
     private String esActivo;

    public AdCabeceraEmpresa() {
    }

    public AdCabeceraEmpresa(String nbCabeceraEmpresa, String nbTituloCabecera, String esActivo) {
       this.nbCabeceraEmpresa = nbCabeceraEmpresa;
       this.nbTituloCabecera = nbTituloCabecera;
       this.esActivo = esActivo;
    }
   
    public Integer getCoCabeceraEmpresa() {
        return this.coCabeceraEmpresa;
    }
    
    public void setCoCabeceraEmpresa(Integer coCabeceraEmpresa) {
        this.coCabeceraEmpresa = coCabeceraEmpresa;
    }
    public String getNbCabeceraEmpresa() {
        return this.nbCabeceraEmpresa;
    }
    
    public void setNbCabeceraEmpresa(String nbCabeceraEmpresa) {
        this.nbCabeceraEmpresa = nbCabeceraEmpresa;
    }
    public String getNbTituloCabecera() {
        return this.nbTituloCabecera;
    }
    
    public void setNbTituloCabecera(String nbTituloCabecera) {
        this.nbTituloCabecera = nbTituloCabecera;
    }
    public String getEsActivo() {
        return this.esActivo;
    }
    
    public void setEsActivo(String esActivo) {
        this.esActivo = esActivo;
    }




}


