package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * AdEstiloPlantilla generated by hbm2java
 */
public class AdEstiloPlantilla  implements java.io.Serializable {


     private Integer coEstiloPlantilla;
     private String nbEstilo;
     private String esVigente;
     private String nbPathImagen;

    public AdEstiloPlantilla() {
    }

    public AdEstiloPlantilla(String nbEstilo, String esVigente, String nbPathImagen) {
       this.nbEstilo = nbEstilo;
       this.esVigente = esVigente;
       this.nbPathImagen = nbPathImagen;
    }
   
    public Integer getCoEstiloPlantilla() {
        return this.coEstiloPlantilla;
    }
    
    public void setCoEstiloPlantilla(Integer coEstiloPlantilla) {
        this.coEstiloPlantilla = coEstiloPlantilla;
    }
    public String getNbEstilo() {
        return this.nbEstilo;
    }
    
    public void setNbEstilo(String nbEstilo) {
        this.nbEstilo = nbEstilo;
    }
    public String getEsVigente() {
        return this.esVigente;
    }
    
    public void setEsVigente(String esVigente) {
        this.esVigente = esVigente;
    }
    public String getNbPathImagen() {
        return this.nbPathImagen;
    }
    
    public void setNbPathImagen(String nbPathImagen) {
        this.nbPathImagen = nbPathImagen;
    }




}


