package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AdGrupoUsuario generated by hbm2java
 */
public class AdGrupoUsuario  implements java.io.Serializable {


     private Short coGrupoUsuario;
     private String nbGrupoUsuario;
     private String nbPortal;
     private Set adPermisoMenus = new HashSet(0);
     private Set adUsuarios = new HashSet(0);

    public AdGrupoUsuario() {
    }

	
    public AdGrupoUsuario(String nbGrupoUsuario, String nbPortal) {
        this.nbGrupoUsuario = nbGrupoUsuario;
        this.nbPortal = nbPortal;
    }
    public AdGrupoUsuario(String nbGrupoUsuario, String nbPortal, Set adPermisoMenus, Set adUsuarios) {
       this.nbGrupoUsuario = nbGrupoUsuario;
       this.nbPortal = nbPortal;
       this.adPermisoMenus = adPermisoMenus;
       this.adUsuarios = adUsuarios;
    }
   
    public Short getCoGrupoUsuario() {
        return this.coGrupoUsuario;
    }
    
    public void setCoGrupoUsuario(Short coGrupoUsuario) {
        this.coGrupoUsuario = coGrupoUsuario;
    }
    public String getNbGrupoUsuario() {
        return this.nbGrupoUsuario;
    }
    
    public void setNbGrupoUsuario(String nbGrupoUsuario) {
        this.nbGrupoUsuario = nbGrupoUsuario;
    }
    public String getNbPortal() {
        return this.nbPortal;
    }
    
    public void setNbPortal(String nbPortal) {
        this.nbPortal = nbPortal;
    }
    public Set getAdPermisoMenus() {
        return this.adPermisoMenus;
    }
    
    public void setAdPermisoMenus(Set adPermisoMenus) {
        this.adPermisoMenus = adPermisoMenus;
    }
    public Set getAdUsuarios() {
        return this.adUsuarios;
    }
    
    public void setAdUsuarios(Set adUsuarios) {
        this.adUsuarios = adUsuarios;
    }




}


