package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AdMenuSistema generated by hbm2java
 */
public class AdMenuSistema  implements java.io.Serializable {


     private Short coMenuSistema;
     private AdMenuSistema adMenuSistema;
     private AdSistema adSistema;
     private String nbMenuSistema;
     private Integer coNivelMenuSistema;
     private String coOpcionMenuSistema;
     private Set adPermisoMenus = new HashSet(0);
     private Set adMenuSistemas = new HashSet(0);

    public AdMenuSistema() {
    }

	
    public AdMenuSistema(AdSistema adSistema, String nbMenuSistema) {
        this.adSistema = adSistema;
        this.nbMenuSistema = nbMenuSistema;
    }
    public AdMenuSistema(AdMenuSistema adMenuSistema, AdSistema adSistema, String nbMenuSistema, Integer coNivelMenuSistema, String coOpcionMenuSistema, Set adPermisoMenus, Set adMenuSistemas) {
       this.adMenuSistema = adMenuSistema;
       this.adSistema = adSistema;
       this.nbMenuSistema = nbMenuSistema;
       this.coNivelMenuSistema = coNivelMenuSistema;
       this.coOpcionMenuSistema = coOpcionMenuSistema;
       this.adPermisoMenus = adPermisoMenus;
       this.adMenuSistemas = adMenuSistemas;
    }
   
    public Short getCoMenuSistema() {
        return this.coMenuSistema;
    }
    
    public void setCoMenuSistema(Short coMenuSistema) {
        this.coMenuSistema = coMenuSistema;
    }
    public AdMenuSistema getAdMenuSistema() {
        return this.adMenuSistema;
    }
    
    public void setAdMenuSistema(AdMenuSistema adMenuSistema) {
        this.adMenuSistema = adMenuSistema;
    }
    public AdSistema getAdSistema() {
        return this.adSistema;
    }
    
    public void setAdSistema(AdSistema adSistema) {
        this.adSistema = adSistema;
    }
    public String getNbMenuSistema() {
        return this.nbMenuSistema;
    }
    
    public void setNbMenuSistema(String nbMenuSistema) {
        this.nbMenuSistema = nbMenuSistema;
    }
    public Integer getCoNivelMenuSistema() {
        return this.coNivelMenuSistema;
    }
    
    public void setCoNivelMenuSistema(Integer coNivelMenuSistema) {
        this.coNivelMenuSistema = coNivelMenuSistema;
    }
    public String getCoOpcionMenuSistema() {
        return this.coOpcionMenuSistema;
    }
    
    public void setCoOpcionMenuSistema(String coOpcionMenuSistema) {
        this.coOpcionMenuSistema = coOpcionMenuSistema;
    }
    public Set getAdPermisoMenus() {
        return this.adPermisoMenus;
    }
    
    public void setAdPermisoMenus(Set adPermisoMenus) {
        this.adPermisoMenus = adPermisoMenus;
    }
    public Set getAdMenuSistemas() {
        return this.adMenuSistemas;
    }
    
    public void setAdMenuSistemas(Set adMenuSistemas) {
        this.adMenuSistemas = adMenuSistemas;
    }




}


