package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AdSistema generated by hbm2java
 */
public class AdSistema  implements java.io.Serializable {


     private Integer coSistema;
     private String nbSistema;
     private String nbClave;
     private Set adMenuSistemas = new HashSet(0);

    public AdSistema() {
    }

	
    public AdSistema(String nbSistema, String nbClave) {
        this.nbSistema = nbSistema;
        this.nbClave = nbClave;
    }
    public AdSistema(String nbSistema, String nbClave, Set adMenuSistemas) {
       this.nbSistema = nbSistema;
       this.nbClave = nbClave;
       this.adMenuSistemas = adMenuSistemas;
    }
   
    public Integer getCoSistema() {
        return this.coSistema;
    }
    
    public void setCoSistema(Integer coSistema) {
        this.coSistema = coSistema;
    }
    public String getNbSistema() {
        return this.nbSistema;
    }
    
    public void setNbSistema(String nbSistema) {
        this.nbSistema = nbSistema;
    }
    public String getNbClave() {
        return this.nbClave;
    }
    
    public void setNbClave(String nbClave) {
        this.nbClave = nbClave;
    }
    public Set getAdMenuSistemas() {
        return this.adMenuSistemas;
    }
    
    public void setAdMenuSistemas(Set adMenuSistemas) {
        this.adMenuSistemas = adMenuSistemas;
    }




}


