package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BeAgencia generated by hbm2java
 */
public class BeAgencia  implements java.io.Serializable {


     private Integer coAgencia;
     private String nbAgencia;
     private Set beColocacions = new HashSet(0);

    public BeAgencia() {
    }

    public BeAgencia(String nbAgencia, Set beColocacions) {
       this.nbAgencia = nbAgencia;
       this.beColocacions = beColocacions;
    }
   
    public Integer getCoAgencia() {
        return this.coAgencia;
    }
    
    public void setCoAgencia(Integer coAgencia) {
        this.coAgencia = coAgencia;
    }
    public String getNbAgencia() {
        return this.nbAgencia;
    }
    
    public void setNbAgencia(String nbAgencia) {
        this.nbAgencia = nbAgencia;
    }
    public Set getBeColocacions() {
        return this.beColocacions;
    }
    
    public void setBeColocacions(Set beColocacions) {
        this.beColocacions = beColocacions;
    }




}


