package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * BeCategoriaCv generated by hbm2java
 */
public class BeCategoriaCv  implements java.io.Serializable {


     private Integer coCategoriaCv;
     private BeCurriculo beCurriculo;
     private int coCategoria;
     private String deEspecifique;

    public BeCategoriaCv() {
    }

	
    public BeCategoriaCv(BeCurriculo beCurriculo, int coCategoria) {
        this.beCurriculo = beCurriculo;
        this.coCategoria = coCategoria;
    }
    public BeCategoriaCv(BeCurriculo beCurriculo, int coCategoria, String deEspecifique) {
       this.beCurriculo = beCurriculo;
       this.coCategoria = coCategoria;
       this.deEspecifique = deEspecifique;
    }
   
    public Integer getCoCategoriaCv() {
        return this.coCategoriaCv;
    }
    
    public void setCoCategoriaCv(Integer coCategoriaCv) {
        this.coCategoriaCv = coCategoriaCv;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public int getCoCategoria() {
        return this.coCategoria;
    }
    
    public void setCoCategoria(int coCategoria) {
        this.coCategoria = coCategoria;
    }
    public String getDeEspecifique() {
        return this.deEspecifique;
    }
    
    public void setDeEspecifique(String deEspecifique) {
        this.deEspecifique = deEspecifique;
    }




}


