package ec.gob.celec.persistencia;
// Generated 27/06/2014 11:55:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BeCatalogo generated by hbm2java
 */
public class BeCatalogo  implements java.io.Serializable {


     private Integer coCatalogo;
     private BeCatalogo beCatalogo;
     private String nbCatalogo;
     private String esCatalogo;
     private short nvCatalogo;
     private Set beIdiomasForCoNombreIdiioma = new HashSet(0);
     private Set beOfertaEmpleosForCoAreaEstudio = new HashSet(0);
     private Set beFormAcademicasForCoNivelEstudio = new HashSet(0);
     private Set bePersonasForCoTipoLicenciaPer = new HashSet(0);
     private Set beIdiomasForCoEscribe = new HashSet(0);
     private Set bePersonasForCoTipoDiscapacidad = new HashSet(0);
     private Set bePersonasForCoProvinciaPer = new HashSet(0);
     private Set beOfertaEmpleosForCoRelaLabOferemp = new HashSet(0);
     private Set beIdiomasForCoHabla = new HashSet(0);
     private Set beRefeEmpresas = new HashSet(0);
     private Set bePersonasForCoNivelEstudios = new HashSet(0);
     private Set beOfertaEmpleosForCoInstruccionOferemp = new HashSet(0);
     private Set beIdiomasForCoEntiende = new HashSet(0);
     private Set beOfertaEmpleosForCoCategoriaOfertaOfe = new HashSet(0);
     private Set beCapacitacions = new HashSet(0);
     private Set beOfertaEmpleosForCoDepartamentoOfe = new HashSet(0);
     private Set beCatalogos = new HashSet(0);
     private Set bePersonasForCoEstadoCivilPer = new HashSet(0);
     private Set beConocimientos = new HashSet(0);
     private Set bePersonasForCoAreaEstudios = new HashSet(0);
     private Set bePersonasForCoPaisResidePer = new HashSet(0);
     private Set bePersonasForCoGeneroPer = new HashSet(0);
     private Set bePersonasForCoTipoIdentificacionPer = new HashSet(0);
     private Set bePersonasForCoGrupoEtnicoPer = new HashSet(0);
     private Set beCalificacionEducacions = new HashSet(0);
     private Set beFormAcademicasForCoAreEstudio = new HashSet(0);

    public BeCatalogo() {
    }

	
    public BeCatalogo(String nbCatalogo, String esCatalogo, short nvCatalogo) {
        this.nbCatalogo = nbCatalogo;
        this.esCatalogo = esCatalogo;
        this.nvCatalogo = nvCatalogo;
    }
    public BeCatalogo(BeCatalogo beCatalogo, String nbCatalogo, String esCatalogo, short nvCatalogo, Set beIdiomasForCoNombreIdiioma, Set beOfertaEmpleosForCoAreaEstudio, Set beFormAcademicasForCoNivelEstudio, Set bePersonasForCoTipoLicenciaPer, Set beIdiomasForCoEscribe, Set bePersonasForCoTipoDiscapacidad, Set bePersonasForCoProvinciaPer, Set beOfertaEmpleosForCoRelaLabOferemp, Set beIdiomasForCoHabla, Set beRefeEmpresas, Set bePersonasForCoNivelEstudios, Set beOfertaEmpleosForCoInstruccionOferemp, Set beIdiomasForCoEntiende, Set beOfertaEmpleosForCoCategoriaOfertaOfe, Set beCapacitacions, Set beOfertaEmpleosForCoDepartamentoOfe, Set beCatalogos, Set bePersonasForCoEstadoCivilPer, Set beConocimientos, Set bePersonasForCoAreaEstudios, Set bePersonasForCoPaisResidePer, Set bePersonasForCoGeneroPer, Set bePersonasForCoTipoIdentificacionPer, Set bePersonasForCoGrupoEtnicoPer, Set beCalificacionEducacions, Set beFormAcademicasForCoAreEstudio) {
       this.beCatalogo = beCatalogo;
       this.nbCatalogo = nbCatalogo;
       this.esCatalogo = esCatalogo;
       this.nvCatalogo = nvCatalogo;
       this.beIdiomasForCoNombreIdiioma = beIdiomasForCoNombreIdiioma;
       this.beOfertaEmpleosForCoAreaEstudio = beOfertaEmpleosForCoAreaEstudio;
       this.beFormAcademicasForCoNivelEstudio = beFormAcademicasForCoNivelEstudio;
       this.bePersonasForCoTipoLicenciaPer = bePersonasForCoTipoLicenciaPer;
       this.beIdiomasForCoEscribe = beIdiomasForCoEscribe;
       this.bePersonasForCoTipoDiscapacidad = bePersonasForCoTipoDiscapacidad;
       this.bePersonasForCoProvinciaPer = bePersonasForCoProvinciaPer;
       this.beOfertaEmpleosForCoRelaLabOferemp = beOfertaEmpleosForCoRelaLabOferemp;
       this.beIdiomasForCoHabla = beIdiomasForCoHabla;
       this.beRefeEmpresas = beRefeEmpresas;
       this.bePersonasForCoNivelEstudios = bePersonasForCoNivelEstudios;
       this.beOfertaEmpleosForCoInstruccionOferemp = beOfertaEmpleosForCoInstruccionOferemp;
       this.beIdiomasForCoEntiende = beIdiomasForCoEntiende;
       this.beOfertaEmpleosForCoCategoriaOfertaOfe = beOfertaEmpleosForCoCategoriaOfertaOfe;
       this.beCapacitacions = beCapacitacions;
       this.beOfertaEmpleosForCoDepartamentoOfe = beOfertaEmpleosForCoDepartamentoOfe;
       this.beCatalogos = beCatalogos;
       this.bePersonasForCoEstadoCivilPer = bePersonasForCoEstadoCivilPer;
       this.beConocimientos = beConocimientos;
       this.bePersonasForCoAreaEstudios = bePersonasForCoAreaEstudios;
       this.bePersonasForCoPaisResidePer = bePersonasForCoPaisResidePer;
       this.bePersonasForCoGeneroPer = bePersonasForCoGeneroPer;
       this.bePersonasForCoTipoIdentificacionPer = bePersonasForCoTipoIdentificacionPer;
       this.bePersonasForCoGrupoEtnicoPer = bePersonasForCoGrupoEtnicoPer;
       this.beCalificacionEducacions = beCalificacionEducacions;
       this.beFormAcademicasForCoAreEstudio = beFormAcademicasForCoAreEstudio;
    }
   
    public Integer getCoCatalogo() {
        return this.coCatalogo;
    }
    
    public void setCoCatalogo(Integer coCatalogo) {
        this.coCatalogo = coCatalogo;
    }
    public BeCatalogo getBeCatalogo() {
        return this.beCatalogo;
    }
    
    public void setBeCatalogo(BeCatalogo beCatalogo) {
        this.beCatalogo = beCatalogo;
    }
    public String getNbCatalogo() {
        return this.nbCatalogo;
    }
    
    public void setNbCatalogo(String nbCatalogo) {
        this.nbCatalogo = nbCatalogo;
    }
    public String getEsCatalogo() {
        return this.esCatalogo;
    }
    
    public void setEsCatalogo(String esCatalogo) {
        this.esCatalogo = esCatalogo;
    }
    public short getNvCatalogo() {
        return this.nvCatalogo;
    }
    
    public void setNvCatalogo(short nvCatalogo) {
        this.nvCatalogo = nvCatalogo;
    }
    public Set getBeIdiomasForCoNombreIdiioma() {
        return this.beIdiomasForCoNombreIdiioma;
    }
    
    public void setBeIdiomasForCoNombreIdiioma(Set beIdiomasForCoNombreIdiioma) {
        this.beIdiomasForCoNombreIdiioma = beIdiomasForCoNombreIdiioma;
    }
    public Set getBeOfertaEmpleosForCoAreaEstudio() {
        return this.beOfertaEmpleosForCoAreaEstudio;
    }
    
    public void setBeOfertaEmpleosForCoAreaEstudio(Set beOfertaEmpleosForCoAreaEstudio) {
        this.beOfertaEmpleosForCoAreaEstudio = beOfertaEmpleosForCoAreaEstudio;
    }
    public Set getBeFormAcademicasForCoNivelEstudio() {
        return this.beFormAcademicasForCoNivelEstudio;
    }
    
    public void setBeFormAcademicasForCoNivelEstudio(Set beFormAcademicasForCoNivelEstudio) {
        this.beFormAcademicasForCoNivelEstudio = beFormAcademicasForCoNivelEstudio;
    }
    public Set getBePersonasForCoTipoLicenciaPer() {
        return this.bePersonasForCoTipoLicenciaPer;
    }
    
    public void setBePersonasForCoTipoLicenciaPer(Set bePersonasForCoTipoLicenciaPer) {
        this.bePersonasForCoTipoLicenciaPer = bePersonasForCoTipoLicenciaPer;
    }
    public Set getBeIdiomasForCoEscribe() {
        return this.beIdiomasForCoEscribe;
    }
    
    public void setBeIdiomasForCoEscribe(Set beIdiomasForCoEscribe) {
        this.beIdiomasForCoEscribe = beIdiomasForCoEscribe;
    }
    public Set getBePersonasForCoTipoDiscapacidad() {
        return this.bePersonasForCoTipoDiscapacidad;
    }
    
    public void setBePersonasForCoTipoDiscapacidad(Set bePersonasForCoTipoDiscapacidad) {
        this.bePersonasForCoTipoDiscapacidad = bePersonasForCoTipoDiscapacidad;
    }
    public Set getBePersonasForCoProvinciaPer() {
        return this.bePersonasForCoProvinciaPer;
    }
    
    public void setBePersonasForCoProvinciaPer(Set bePersonasForCoProvinciaPer) {
        this.bePersonasForCoProvinciaPer = bePersonasForCoProvinciaPer;
    }
    public Set getBeOfertaEmpleosForCoRelaLabOferemp() {
        return this.beOfertaEmpleosForCoRelaLabOferemp;
    }
    
    public void setBeOfertaEmpleosForCoRelaLabOferemp(Set beOfertaEmpleosForCoRelaLabOferemp) {
        this.beOfertaEmpleosForCoRelaLabOferemp = beOfertaEmpleosForCoRelaLabOferemp;
    }
    public Set getBeIdiomasForCoHabla() {
        return this.beIdiomasForCoHabla;
    }
    
    public void setBeIdiomasForCoHabla(Set beIdiomasForCoHabla) {
        this.beIdiomasForCoHabla = beIdiomasForCoHabla;
    }
    public Set getBeRefeEmpresas() {
        return this.beRefeEmpresas;
    }
    
    public void setBeRefeEmpresas(Set beRefeEmpresas) {
        this.beRefeEmpresas = beRefeEmpresas;
    }
    public Set getBePersonasForCoNivelEstudios() {
        return this.bePersonasForCoNivelEstudios;
    }
    
    public void setBePersonasForCoNivelEstudios(Set bePersonasForCoNivelEstudios) {
        this.bePersonasForCoNivelEstudios = bePersonasForCoNivelEstudios;
    }
    public Set getBeOfertaEmpleosForCoInstruccionOferemp() {
        return this.beOfertaEmpleosForCoInstruccionOferemp;
    }
    
    public void setBeOfertaEmpleosForCoInstruccionOferemp(Set beOfertaEmpleosForCoInstruccionOferemp) {
        this.beOfertaEmpleosForCoInstruccionOferemp = beOfertaEmpleosForCoInstruccionOferemp;
    }
    public Set getBeIdiomasForCoEntiende() {
        return this.beIdiomasForCoEntiende;
    }
    
    public void setBeIdiomasForCoEntiende(Set beIdiomasForCoEntiende) {
        this.beIdiomasForCoEntiende = beIdiomasForCoEntiende;
    }
    public Set getBeOfertaEmpleosForCoCategoriaOfertaOfe() {
        return this.beOfertaEmpleosForCoCategoriaOfertaOfe;
    }
    
    public void setBeOfertaEmpleosForCoCategoriaOfertaOfe(Set beOfertaEmpleosForCoCategoriaOfertaOfe) {
        this.beOfertaEmpleosForCoCategoriaOfertaOfe = beOfertaEmpleosForCoCategoriaOfertaOfe;
    }
    public Set getBeCapacitacions() {
        return this.beCapacitacions;
    }
    
    public void setBeCapacitacions(Set beCapacitacions) {
        this.beCapacitacions = beCapacitacions;
    }
    public Set getBeOfertaEmpleosForCoDepartamentoOfe() {
        return this.beOfertaEmpleosForCoDepartamentoOfe;
    }
    
    public void setBeOfertaEmpleosForCoDepartamentoOfe(Set beOfertaEmpleosForCoDepartamentoOfe) {
        this.beOfertaEmpleosForCoDepartamentoOfe = beOfertaEmpleosForCoDepartamentoOfe;
    }
    public Set getBeCatalogos() {
        return this.beCatalogos;
    }
    
    public void setBeCatalogos(Set beCatalogos) {
        this.beCatalogos = beCatalogos;
    }
    public Set getBePersonasForCoEstadoCivilPer() {
        return this.bePersonasForCoEstadoCivilPer;
    }
    
    public void setBePersonasForCoEstadoCivilPer(Set bePersonasForCoEstadoCivilPer) {
        this.bePersonasForCoEstadoCivilPer = bePersonasForCoEstadoCivilPer;
    }
    public Set getBeConocimientos() {
        return this.beConocimientos;
    }
    
    public void setBeConocimientos(Set beConocimientos) {
        this.beConocimientos = beConocimientos;
    }
    public Set getBePersonasForCoAreaEstudios() {
        return this.bePersonasForCoAreaEstudios;
    }
    
    public void setBePersonasForCoAreaEstudios(Set bePersonasForCoAreaEstudios) {
        this.bePersonasForCoAreaEstudios = bePersonasForCoAreaEstudios;
    }
    public Set getBePersonasForCoPaisResidePer() {
        return this.bePersonasForCoPaisResidePer;
    }
    
    public void setBePersonasForCoPaisResidePer(Set bePersonasForCoPaisResidePer) {
        this.bePersonasForCoPaisResidePer = bePersonasForCoPaisResidePer;
    }
    public Set getBePersonasForCoGeneroPer() {
        return this.bePersonasForCoGeneroPer;
    }
    
    public void setBePersonasForCoGeneroPer(Set bePersonasForCoGeneroPer) {
        this.bePersonasForCoGeneroPer = bePersonasForCoGeneroPer;
    }
    public Set getBePersonasForCoTipoIdentificacionPer() {
        return this.bePersonasForCoTipoIdentificacionPer;
    }
    
    public void setBePersonasForCoTipoIdentificacionPer(Set bePersonasForCoTipoIdentificacionPer) {
        this.bePersonasForCoTipoIdentificacionPer = bePersonasForCoTipoIdentificacionPer;
    }
    public Set getBePersonasForCoGrupoEtnicoPer() {
        return this.bePersonasForCoGrupoEtnicoPer;
    }
    
    public void setBePersonasForCoGrupoEtnicoPer(Set bePersonasForCoGrupoEtnicoPer) {
        this.bePersonasForCoGrupoEtnicoPer = bePersonasForCoGrupoEtnicoPer;
    }
    public Set getBeCalificacionEducacions() {
        return this.beCalificacionEducacions;
    }
    
    public void setBeCalificacionEducacions(Set beCalificacionEducacions) {
        this.beCalificacionEducacions = beCalificacionEducacions;
    }
    public Set getBeFormAcademicasForCoAreEstudio() {
        return this.beFormAcademicasForCoAreEstudio;
    }
    
    public void setBeFormAcademicasForCoAreEstudio(Set beFormAcademicasForCoAreEstudio) {
        this.beFormAcademicasForCoAreEstudio = beFormAcademicasForCoAreEstudio;
    }




}


