package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * BeCapacitacion generated by hbm2java
 */
public class BeCapacitacion  implements java.io.Serializable {


     private Integer coCapacitacion;
     private BeCatalogo beCatalogo;
     private BeCurriculo beCurriculo;
     private String nbCursoRealizado;
     private String nbInstitucion;
     private String nbLugar;
     private Integer nuAnioGrado;
     private Integer nuHoras;
     private String nbDescripcion;
     private String esEstado;

    public BeCapacitacion() {
    }

	
    public BeCapacitacion(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BeCapacitacion(BeCatalogo beCatalogo, BeCurriculo beCurriculo, String nbCursoRealizado, String nbInstitucion, String nbLugar, Integer nuAnioGrado, Integer nuHoras, String nbDescripcion, String esEstado) {
       this.beCatalogo = beCatalogo;
       this.beCurriculo = beCurriculo;
       this.nbCursoRealizado = nbCursoRealizado;
       this.nbInstitucion = nbInstitucion;
       this.nbLugar = nbLugar;
       this.nuAnioGrado = nuAnioGrado;
       this.nuHoras = nuHoras;
       this.nbDescripcion = nbDescripcion;
       this.esEstado = esEstado;
    }
   
    public Integer getCoCapacitacion() {
        return this.coCapacitacion;
    }
    
    public void setCoCapacitacion(Integer coCapacitacion) {
        this.coCapacitacion = coCapacitacion;
    }
    public BeCatalogo getBeCatalogo() {
        return this.beCatalogo;
    }
    
    public void setBeCatalogo(BeCatalogo beCatalogo) {
        this.beCatalogo = beCatalogo;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public String getNbCursoRealizado() {
        return this.nbCursoRealizado;
    }
    
    public void setNbCursoRealizado(String nbCursoRealizado) {
        this.nbCursoRealizado = nbCursoRealizado;
    }
    public String getNbInstitucion() {
        return this.nbInstitucion;
    }
    
    public void setNbInstitucion(String nbInstitucion) {
        this.nbInstitucion = nbInstitucion;
    }
    public String getNbLugar() {
        return this.nbLugar;
    }
    
    public void setNbLugar(String nbLugar) {
        this.nbLugar = nbLugar;
    }
    public Integer getNuAnioGrado() {
        return this.nuAnioGrado;
    }
    
    public void setNuAnioGrado(Integer nuAnioGrado) {
        this.nuAnioGrado = nuAnioGrado;
    }
    public Integer getNuHoras() {
        return this.nuHoras;
    }
    
    public void setNuHoras(Integer nuHoras) {
        this.nuHoras = nuHoras;
    }
    public String getNbDescripcion() {
        return this.nbDescripcion;
    }
    
    public void setNbDescripcion(String nbDescripcion) {
        this.nbDescripcion = nbDescripcion;
    }
    public String getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(String esEstado) {
        this.esEstado = esEstado;
    }




}


