package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * BeCategPeso generated by hbm2java
 */
public class BeCategPeso  implements java.io.Serializable {


     private Short coCategPeso;
     private String nbCategPeso;
     private Set bePesoOfertas = new HashSet(0);
     private String vaTipoCalificacion;

    public BeCategPeso() {
    }

	
    public BeCategPeso(String nbCategPeso) {
        this.nbCategPeso = nbCategPeso;
    }
    public BeCategPeso(String nbCategPeso, Set bePesoOfertas) {
       this.nbCategPeso = nbCategPeso;
       this.bePesoOfertas = bePesoOfertas;
    }
   
    public Short getCoCategPeso() {
        return this.coCategPeso;
    }
    
    public void setCoCategPeso(Short coCategPeso) {
        this.coCategPeso = coCategPeso;
    }
    public String getNbCategPeso() {
        return this.nbCategPeso;
    }
    
    public void setNbCategPeso(String nbCategPeso) {
        this.nbCategPeso = nbCategPeso;
    }
    public Set getBePesoOfertas() {
        return this.bePesoOfertas;
    }
    
    public void setBePesoOfertas(Set bePesoOfertas) {
        this.bePesoOfertas = bePesoOfertas;
    }

    /**
     * @return the vaTipoCalificacion
     */
    public String getVaTipoCalificacion() {
        return vaTipoCalificacion;
    }

    /**
     * @param vaTipoCalificacion the vaTipoCalificacion to set
     */
    public void setVaTipoCalificacion(String vaTipoCalificacion) {
        this.vaTipoCalificacion = vaTipoCalificacion;
    }




}


