package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * BeConocimiento generated by hbm2java
 */
public class BeConocimiento  implements java.io.Serializable {


     private Integer coConocimiento;
     private BeCatalogo beCatalogo;
     private BeCurriculo beCurriculo;
     private String nbDescripcion;
     private String esEstado;

    public BeConocimiento() {
    }

	
    public BeConocimiento(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BeConocimiento(BeCatalogo beCatalogo, BeCurriculo beCurriculo, String nbDescripcion, String esEstado) {
       this.beCatalogo = beCatalogo;
       this.beCurriculo = beCurriculo;
       this.nbDescripcion = nbDescripcion;
       this.esEstado = esEstado;
    }
   
    public Integer getCoConocimiento() {
        return this.coConocimiento;
    }
    
    public void setCoConocimiento(Integer coConocimiento) {
        this.coConocimiento = coConocimiento;
    }
    public BeCatalogo getBeCatalogo() {
        return this.beCatalogo;
    }
    
    public void setBeCatalogo(BeCatalogo beCatalogo) {
        this.beCatalogo = beCatalogo;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public String getNbDescripcion() {
        return this.nbDescripcion;
    }
    
    public void setNbDescripcion(String nbDescripcion) {
        this.nbDescripcion = nbDescripcion;
    }
    public String getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(String esEstado) {
        this.esEstado = esEstado;
    }




}


