package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BeComentarioCv generated by hbm2java
 */
public class BeComentarioCv  implements java.io.Serializable {


     private Integer coComentarioCv;
     private BeCurriculo beCurriculo;
     private String nbComentario;
     private Date feComenatrio;

    public BeComentarioCv() {
    }

    public BeComentarioCv(BeCurriculo beCurriculo, String nbComentario, Date feComenatrio) {
       this.beCurriculo = beCurriculo;
       this.nbComentario = nbComentario;
       this.feComenatrio = feComenatrio;
    }
   
    public Integer getCoComentarioCv() {
        return this.coComentarioCv;
    }
    
    public void setCoComentarioCv(Integer coComentarioCv) {
        this.coComentarioCv = coComentarioCv;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public String getNbComentario() {
        return this.nbComentario;
    }
    
    public void setNbComentario(String nbComentario) {
        this.nbComentario = nbComentario;
    }
    public Date getFeComenatrio() {
        return this.feComenatrio;
    }
    
    public void setFeComenatrio(Date feComenatrio) {
        this.feComenatrio = feComenatrio;
    }




}


