package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * BeComentarioOferta generated by hbm2java
 */
public class BeComentarioOferta  implements java.io.Serializable {


     private Integer coComentarioOferta;
     private BeOfertaEmpleo beOfertaEmpleo;
     private String nbComentario;

    public BeComentarioOferta() {
    }

	
    public BeComentarioOferta(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public BeComentarioOferta(BeOfertaEmpleo beOfertaEmpleo, String nbComentario) {
       this.beOfertaEmpleo = beOfertaEmpleo;
       this.nbComentario = nbComentario;
    }
   
    public Integer getCoComentarioOferta() {
        return this.coComentarioOferta;
    }
    
    public void setCoComentarioOferta(Integer coComentarioOferta) {
        this.coComentarioOferta = coComentarioOferta;
    }
    public BeOfertaEmpleo getBeOfertaEmpleo() {
        return this.beOfertaEmpleo;
    }
    
    public void setBeOfertaEmpleo(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public String getNbComentario() {
        return this.nbComentario;
    }
    
    public void setNbComentario(String nbComentario) {
        this.nbComentario = nbComentario;
    }




}


