package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BeColocacion generated by hbm2java
 */
public class BeColocacion  implements java.io.Serializable {


     private Integer coColocacion;
     private AdUsuario adUsuario;
     private BeOfertaEmpleo beOfertaEmpleo;
     private BeCurriculo beCurriculo;
     private BeAgencia beAgencia;
     private Date feContratadoColocacion;
     private String deSigueColocado;
     private String nbEmpresa;
     private String nbContacto;
     private String numTelefono;
     private Set beSegColocacions = new HashSet(0);

    public BeColocacion() {
    }

	
    public BeColocacion(AdUsuario adUsuario, BeOfertaEmpleo beOfertaEmpleo, BeAgencia beAgencia) {
        this.adUsuario = adUsuario;
        this.beOfertaEmpleo = beOfertaEmpleo;
        this.beAgencia = beAgencia;
    }
    public BeColocacion(AdUsuario adUsuario, BeOfertaEmpleo beOfertaEmpleo, BeCurriculo beCurriculo, BeAgencia beAgencia, Date feContratadoColocacion, String deSigueColocado, String nbEmpresa, String nbContacto, String numTelefono, Set beSegColocacions) {
       this.adUsuario = adUsuario;
       this.beOfertaEmpleo = beOfertaEmpleo;
       this.beCurriculo = beCurriculo;
       this.beAgencia = beAgencia;
       this.feContratadoColocacion = feContratadoColocacion;
       this.deSigueColocado = deSigueColocado;
       this.nbEmpresa = nbEmpresa;
       this.nbContacto = nbContacto;
       this.numTelefono = numTelefono;
       this.beSegColocacions = beSegColocacions;
    }
   
    public Integer getCoColocacion() {
        return this.coColocacion;
    }
    
    public void setCoColocacion(Integer coColocacion) {
        this.coColocacion = coColocacion;
    }
    public AdUsuario getAdUsuario() {
        return this.adUsuario;
    }
    
    public void setAdUsuario(AdUsuario adUsuario) {
        this.adUsuario = adUsuario;
    }
    public BeOfertaEmpleo getBeOfertaEmpleo() {
        return this.beOfertaEmpleo;
    }
    
    public void setBeOfertaEmpleo(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BeAgencia getBeAgencia() {
        return this.beAgencia;
    }
    
    public void setBeAgencia(BeAgencia beAgencia) {
        this.beAgencia = beAgencia;
    }
    public Date getFeContratadoColocacion() {
        return this.feContratadoColocacion;
    }
    
    public void setFeContratadoColocacion(Date feContratadoColocacion) {
        this.feContratadoColocacion = feContratadoColocacion;
    }
    public String getDeSigueColocado() {
        return this.deSigueColocado;
    }
    
    public void setDeSigueColocado(String deSigueColocado) {
        this.deSigueColocado = deSigueColocado;
    }
    public String getNbEmpresa() {
        return this.nbEmpresa;
    }
    
    public void setNbEmpresa(String nbEmpresa) {
        this.nbEmpresa = nbEmpresa;
    }
    public String getNbContacto() {
        return this.nbContacto;
    }
    
    public void setNbContacto(String nbContacto) {
        this.nbContacto = nbContacto;
    }
    public String getNumTelefono() {
        return this.numTelefono;
    }
    
    public void setNumTelefono(String numTelefono) {
        this.numTelefono = numTelefono;
    }
    public Set getBeSegColocacions() {
        return this.beSegColocacions;
    }
    
    public void setBeSegColocacions(Set beSegColocacions) {
        this.beSegColocacions = beSegColocacions;
    }




}


