package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * BeEvaluacionCv generated by hbm2java
 */
public class BeEvaluacionCv  implements java.io.Serializable {


     private Integer coEvaluacionCv;
     private BePesoOferta bePesoOferta;
     private BeSelecionCvOfer beSelecionCvOfer;
     private BigDecimal vaEvaluacionCv;

    public BeEvaluacionCv() {
    }

    public BeEvaluacionCv(BePesoOferta bePesoOferta, BeSelecionCvOfer beSelecionCvOfer, BigDecimal vaEvaluacionCv) {
       this.bePesoOferta = bePesoOferta;
       this.beSelecionCvOfer = beSelecionCvOfer;
       this.vaEvaluacionCv = vaEvaluacionCv;
    }
   
    public Integer getCoEvaluacionCv() {
        return this.coEvaluacionCv;
    }
    
    public void setCoEvaluacionCv(Integer coEvaluacionCv) {
        this.coEvaluacionCv = coEvaluacionCv;
    }
    public BePesoOferta getBePesoOferta() {
        return this.bePesoOferta;
    }
    
    public void setBePesoOferta(BePesoOferta bePesoOferta) {
        this.bePesoOferta = bePesoOferta;
    }
    public BeSelecionCvOfer getBeSelecionCvOfer() {
        return this.beSelecionCvOfer;
    }
    
    public void setBeSelecionCvOfer(BeSelecionCvOfer beSelecionCvOfer) {
        this.beSelecionCvOfer = beSelecionCvOfer;
    }
    public BigDecimal getVaEvaluacionCv() {
        return this.vaEvaluacionCv;
    }
    
    public void setVaEvaluacionCv(BigDecimal vaEvaluacionCv) {
        this.vaEvaluacionCv = vaEvaluacionCv;
    }




}


