package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BeExpLaboral generated by hbm2java
 */
public class BeExpLaboral  implements java.io.Serializable {


     private Integer coExpLaboral;
     private BeCurriculo beCurriculo;
     private String nbExpLaboral;
     private String nbCargoExpLaboral;
     private Date feIngresoExpLaboral;
     private Date feSalidaExpLaboral;
     private String nuTelefonoExpLaboral;
     private String nbContactoExpLaboral;
     private Integer coIndustria;
     private Integer coTipoEmpresas;
     private String nbEmpresa;
     private String nbCiudad;
     private Integer nuTiempoMeses;
     private String esEstado;

    public BeExpLaboral() {
    }

	
    public BeExpLaboral(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BeExpLaboral(BeCurriculo beCurriculo, String nbExpLaboral, String nbCargoExpLaboral, Date feIngresoExpLaboral, Date feSalidaExpLaboral, String nuTelefonoExpLaboral, String nbContactoExpLaboral, Integer coIndustria, Integer coTipoEmpresas, String nbEmpresa, String nbCiudad, Integer nuTiempoMeses, String esEstado) {
       this.beCurriculo = beCurriculo;
       this.nbExpLaboral = nbExpLaboral;
       this.nbCargoExpLaboral = nbCargoExpLaboral;
       this.feIngresoExpLaboral = feIngresoExpLaboral;
       this.feSalidaExpLaboral = feSalidaExpLaboral;
       this.nuTelefonoExpLaboral = nuTelefonoExpLaboral;
       this.nbContactoExpLaboral = nbContactoExpLaboral;
       this.coIndustria = coIndustria;
       this.coTipoEmpresas = coTipoEmpresas;
       this.nbEmpresa = nbEmpresa;
       this.nbCiudad = nbCiudad;
       this.nuTiempoMeses = nuTiempoMeses;
       this.esEstado = esEstado;
    }
   
    public Integer getCoExpLaboral() {
        return this.coExpLaboral;
    }
    
    public void setCoExpLaboral(Integer coExpLaboral) {
        this.coExpLaboral = coExpLaboral;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public String getNbExpLaboral() {
        return this.nbExpLaboral;
    }
    
    public void setNbExpLaboral(String nbExpLaboral) {
        this.nbExpLaboral = nbExpLaboral;
    }
    public String getNbCargoExpLaboral() {
        return this.nbCargoExpLaboral;
    }
    
    public void setNbCargoExpLaboral(String nbCargoExpLaboral) {
        this.nbCargoExpLaboral = nbCargoExpLaboral;
    }
    public Date getFeIngresoExpLaboral() {
        return this.feIngresoExpLaboral;
    }
    
    public void setFeIngresoExpLaboral(Date feIngresoExpLaboral) {
        this.feIngresoExpLaboral = feIngresoExpLaboral;
    }
    public Date getFeSalidaExpLaboral() {
        return this.feSalidaExpLaboral;
    }
    
    public void setFeSalidaExpLaboral(Date feSalidaExpLaboral) {
        this.feSalidaExpLaboral = feSalidaExpLaboral;
    }
    public String getNuTelefonoExpLaboral() {
        return this.nuTelefonoExpLaboral;
    }
    
    public void setNuTelefonoExpLaboral(String nuTelefonoExpLaboral) {
        this.nuTelefonoExpLaboral = nuTelefonoExpLaboral;
    }
    public String getNbContactoExpLaboral() {
        return this.nbContactoExpLaboral;
    }
    
    public void setNbContactoExpLaboral(String nbContactoExpLaboral) {
        this.nbContactoExpLaboral = nbContactoExpLaboral;
    }
    public Integer getCoIndustria() {
        return this.coIndustria;
    }
    
    public void setCoIndustria(Integer coIndustria) {
        this.coIndustria = coIndustria;
    }
    public Integer getCoTipoEmpresas() {
        return this.coTipoEmpresas;
    }
    
    public void setCoTipoEmpresas(Integer coTipoEmpresas) {
        this.coTipoEmpresas = coTipoEmpresas;
    }
    public String getNbEmpresa() {
        return this.nbEmpresa;
    }
    
    public void setNbEmpresa(String nbEmpresa) {
        this.nbEmpresa = nbEmpresa;
    }
    public String getNbCiudad() {
        return this.nbCiudad;
    }
    
    public void setNbCiudad(String nbCiudad) {
        this.nbCiudad = nbCiudad;
    }
    public Integer getNuTiempoMeses() {
        return this.nuTiempoMeses;
    }
    
    public void setNuTiempoMeses(Integer nuTiempoMeses) {
        this.nuTiempoMeses = nuTiempoMeses;
    }
    public String getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(String esEstado) {
        this.esEstado = esEstado;
    }




}


