package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * BeFormAcademica generated by hbm2java
 */
public class BeFormAcademica  implements java.io.Serializable {


     private Integer coFormaAcademica;
     private BeCatalogo beCatalogoByCoNivelEstudio;
     private BeCatalogo beCatalogoByCoAreEstudio;
     private BeCurriculo beCurriculo;
     private String nbInstitucion;
     private String nbEstudioRealizado;
     private Date feInicioFormacade;
     private Date feFinFormacade;
     private String nbPais;
     private Integer nuHoras;
     private String esFormacionAbt;
     private Integer nuAnioGrado;
     private Integer nuNumeroSenescyt;
     private String esEstado;

    public BeFormAcademica() {
    }

	
    public BeFormAcademica(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BeFormAcademica(BeCatalogo beCatalogoByCoNivelEstudio, BeCatalogo beCatalogoByCoAreEstudio, BeCurriculo beCurriculo, String nbInstitucion, String nbEstudioRealizado, Date feInicioFormacade, Date feFinFormacade, String nbPais, Integer nuHoras, String esFormacionAbt, Integer nuAnioGrado, Integer nuNumeroSenescyt, String esEstado) {
       this.beCatalogoByCoNivelEstudio = beCatalogoByCoNivelEstudio;
       this.beCatalogoByCoAreEstudio = beCatalogoByCoAreEstudio;
       this.beCurriculo = beCurriculo;
       this.nbInstitucion = nbInstitucion;
       this.nbEstudioRealizado = nbEstudioRealizado;
       this.feInicioFormacade = feInicioFormacade;
       this.feFinFormacade = feFinFormacade;
       this.nbPais = nbPais;
       this.nuHoras = nuHoras;
       this.esFormacionAbt = esFormacionAbt;
       this.nuAnioGrado = nuAnioGrado;
       this.nuNumeroSenescyt = nuNumeroSenescyt;
       this.esEstado = esEstado;
    }
   
    public Integer getCoFormaAcademica() {
        return this.coFormaAcademica;
    }
    
    public void setCoFormaAcademica(Integer coFormaAcademica) {
        this.coFormaAcademica = coFormaAcademica;
    }
    public BeCatalogo getBeCatalogoByCoNivelEstudio() {
        return this.beCatalogoByCoNivelEstudio;
    }
    
    public void setBeCatalogoByCoNivelEstudio(BeCatalogo beCatalogoByCoNivelEstudio) {
        this.beCatalogoByCoNivelEstudio = beCatalogoByCoNivelEstudio;
    }
    public BeCatalogo getBeCatalogoByCoAreEstudio() {
        return this.beCatalogoByCoAreEstudio;
    }
    
    public void setBeCatalogoByCoAreEstudio(BeCatalogo beCatalogoByCoAreEstudio) {
        this.beCatalogoByCoAreEstudio = beCatalogoByCoAreEstudio;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public String getNbInstitucion() {
        return this.nbInstitucion;
    }
    
    public void setNbInstitucion(String nbInstitucion) {
        this.nbInstitucion = nbInstitucion;
    }
    public String getNbEstudioRealizado() {
        return this.nbEstudioRealizado;
    }
    
    public void setNbEstudioRealizado(String nbEstudioRealizado) {
        this.nbEstudioRealizado = nbEstudioRealizado;
    }
    public Date getFeInicioFormacade() {
        return this.feInicioFormacade;
    }
    
    public void setFeInicioFormacade(Date feInicioFormacade) {
        this.feInicioFormacade = feInicioFormacade;
    }
    public Date getFeFinFormacade() {
        return this.feFinFormacade;
    }
    
    public void setFeFinFormacade(Date feFinFormacade) {
        this.feFinFormacade = feFinFormacade;
    }
    public String getNbPais() {
        return this.nbPais;
    }
    
    public void setNbPais(String nbPais) {
        this.nbPais = nbPais;
    }
    public Integer getNuHoras() {
        return this.nuHoras;
    }
    
    public void setNuHoras(Integer nuHoras) {
        this.nuHoras = nuHoras;
    }
    public String getEsFormacionAbt() {
        return this.esFormacionAbt;
    }
    
    public void setEsFormacionAbt(String esFormacionAbt) {
        this.esFormacionAbt = esFormacionAbt;
    }
    public Integer getNuAnioGrado() {
        return this.nuAnioGrado;
    }
    
    public void setNuAnioGrado(Integer nuAnioGrado) {
        this.nuAnioGrado = nuAnioGrado;
    }
    public Integer getNuNumeroSenescyt() {
        return this.nuNumeroSenescyt;
    }
    
    public void setNuNumeroSenescyt(Integer nuNumeroSenescyt) {
        this.nuNumeroSenescyt = nuNumeroSenescyt;
    }
    public String getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(String esEstado) {
        this.esEstado = esEstado;
    }




}


