package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * BeModoEmpleoOferta generated by hbm2java
 */
public class BeModoEmpleoOferta  implements java.io.Serializable {


     private Integer coModoEmpleoOferta;
     private BeOfertaEmpleo beOfertaEmpleo;
     private String coModoEmplOferta;
     private String deEspecifique;

    public BeModoEmpleoOferta() {
    }

	
    public BeModoEmpleoOferta(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public BeModoEmpleoOferta(BeOfertaEmpleo beOfertaEmpleo, String coModoEmplOferta, String deEspecifique) {
       this.beOfertaEmpleo = beOfertaEmpleo;
       this.coModoEmplOferta = coModoEmplOferta;
       this.deEspecifique = deEspecifique;
    }
   
    public Integer getCoModoEmpleoOferta() {
        return this.coModoEmpleoOferta;
    }
    
    public void setCoModoEmpleoOferta(Integer coModoEmpleoOferta) {
        this.coModoEmpleoOferta = coModoEmpleoOferta;
    }
    public BeOfertaEmpleo getBeOfertaEmpleo() {
        return this.beOfertaEmpleo;
    }
    
    public void setBeOfertaEmpleo(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public String getCoModoEmplOferta() {
        return this.coModoEmplOferta;
    }
    
    public void setCoModoEmplOferta(String coModoEmplOferta) {
        this.coModoEmplOferta = coModoEmplOferta;
    }
    public String getDeEspecifique() {
        return this.deEspecifique;
    }
    
    public void setDeEspecifique(String deEspecifique) {
        this.deEspecifique = deEspecifique;
    }




}


