package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BePersona generated by hbm2java
 */
public class BePersona  implements java.io.Serializable {


     private Integer coPersona;
     private BeCatalogo beCatalogoByCoAreaEstudios;
     private BeCatalogo beCatalogoByCoEstadoCivilPer;
     private BeCatalogo beCatalogoByCoTipoIdentificacionPer;
     private BeCatalogo beCatalogoByCoGeneroPer;
     private AdUsuario adUsuario;
     private BeCatalogo beCatalogoByCoPaisResidePer;
     private BeCatalogo beCatalogoByCoTipoLicenciaPer;
     private BeCatalogo beCatalogoByCoTipoDiscapacidad;
     private BeCatalogo beCatalogoByCoProvinciaPer;
     private BeCatalogo beCatalogoByCoGrupoEtnicoPer;
     private BeCatalogo beCatalogoByCoNivelEstudios;
     private String nbPersona;
     private String apPersona;
     private String nuIdentificaciobPer;
     private String deDomicilioPer;
     private Integer coCantonPer;
     private Integer coSectorPer;
     private String deBarrioPer;
     private String nuTelefonoPer;
     private String nuCelularFono;
     private Date feNacimientoPer;
     private String deLugarNacimientoPer;
     private String deNacionalidadPer;
     private String deEmailPer;
     private Integer coNivelAcademicoPer;
     private Integer nuAnioAprobadosPer;
     private String deTituProfesionPer;
     private String coSituLaboralPer;
     private String coExpLaboralPer;
     private byte[] imFotoPer;
     private String dePotoPer;
     private String esPersona;
     private Integer coInstruccion;
     private Date feModifica;
     private String vaDiscapacidadPer;
     private String vaExtranjeroPer;
     private Integer coPaisOrigenPer;
     private String nbCiudadResidePer;
     private Date feResidePer;
     private Integer coCondicionMigratoriaPer;
     private Integer nuCargaFamiliarPer;
     private String vaPoseeLincenciaPer;
     private String nuPorcentajeDiscapacidadPer;
     private String vaDisponibilidadParaViajarPer;
     private String deCantonPer;
     private String nuCarnetConadisPer;
     private Set beCurriculos = new HashSet(0);
     private Set beEmpresas = new HashSet(0);

    public BePersona() {
    }

	
    public BePersona(BeCatalogo beCatalogoByCoTipoIdentificacionPer, AdUsuario adUsuario, String nbPersona, String apPersona, String nuIdentificaciobPer, String nuTelefonoPer, String esPersona) {
        this.beCatalogoByCoTipoIdentificacionPer = beCatalogoByCoTipoIdentificacionPer;
        this.adUsuario = adUsuario;
        this.nbPersona = nbPersona;
        this.apPersona = apPersona;
        this.nuIdentificaciobPer = nuIdentificaciobPer;
        this.nuTelefonoPer = nuTelefonoPer;
        this.esPersona = esPersona;
    }
    public BePersona(BeCatalogo beCatalogoByCoAreaEstudios, BeCatalogo beCatalogoByCoEstadoCivilPer, BeCatalogo beCatalogoByCoTipoIdentificacionPer, BeCatalogo beCatalogoByCoGeneroPer, AdUsuario adUsuario, BeCatalogo beCatalogoByCoPaisResidePer, BeCatalogo beCatalogoByCoTipoLicenciaPer, BeCatalogo beCatalogoByCoTipoDiscapacidad, BeCatalogo beCatalogoByCoProvinciaPer, BeCatalogo beCatalogoByCoGrupoEtnicoPer, BeCatalogo beCatalogoByCoNivelEstudios, String nbPersona, String apPersona, String nuIdentificaciobPer, String deDomicilioPer, Integer coCantonPer, Integer coSectorPer, String deBarrioPer, String nuTelefonoPer, String nuCelularFono, Date feNacimientoPer, String deLugarNacimientoPer, String deNacionalidadPer, String deEmailPer, Integer coNivelAcademicoPer, Integer nuAnioAprobadosPer, String deTituProfesionPer, String coSituLaboralPer, String coExpLaboralPer, byte[] imFotoPer, String dePotoPer, String esPersona, Integer coInstruccion, Date feModifica, String vaDiscapacidadPer, String vaExtranjeroPer, Integer coPaisOrigenPer, String nbCiudadResidePer, Date feResidePer, Integer coCondicionMigratoriaPer, Integer nuCargaFamiliarPer, String vaPoseeLincenciaPer, String nuPorcentajeDiscapacidadPer, String vaDisponibilidadParaViajarPer, String deCantonPer, String nuCarnetConadisPer, Set beCurriculos, Set beEmpresas) {
       this.beCatalogoByCoAreaEstudios = beCatalogoByCoAreaEstudios;
       this.beCatalogoByCoEstadoCivilPer = beCatalogoByCoEstadoCivilPer;
       this.beCatalogoByCoTipoIdentificacionPer = beCatalogoByCoTipoIdentificacionPer;
       this.beCatalogoByCoGeneroPer = beCatalogoByCoGeneroPer;
       this.adUsuario = adUsuario;
       this.beCatalogoByCoPaisResidePer = beCatalogoByCoPaisResidePer;
       this.beCatalogoByCoTipoLicenciaPer = beCatalogoByCoTipoLicenciaPer;
       this.beCatalogoByCoTipoDiscapacidad = beCatalogoByCoTipoDiscapacidad;
       this.beCatalogoByCoProvinciaPer = beCatalogoByCoProvinciaPer;
       this.beCatalogoByCoGrupoEtnicoPer = beCatalogoByCoGrupoEtnicoPer;
       this.beCatalogoByCoNivelEstudios = beCatalogoByCoNivelEstudios;
       this.nbPersona = nbPersona;
       this.apPersona = apPersona;
       this.nuIdentificaciobPer = nuIdentificaciobPer;
       this.deDomicilioPer = deDomicilioPer;
       this.coCantonPer = coCantonPer;
       this.coSectorPer = coSectorPer;
       this.deBarrioPer = deBarrioPer;
       this.nuTelefonoPer = nuTelefonoPer;
       this.nuCelularFono = nuCelularFono;
       this.feNacimientoPer = feNacimientoPer;
       this.deLugarNacimientoPer = deLugarNacimientoPer;
       this.deNacionalidadPer = deNacionalidadPer;
       this.deEmailPer = deEmailPer;
       this.coNivelAcademicoPer = coNivelAcademicoPer;
       this.nuAnioAprobadosPer = nuAnioAprobadosPer;
       this.deTituProfesionPer = deTituProfesionPer;
       this.coSituLaboralPer = coSituLaboralPer;
       this.coExpLaboralPer = coExpLaboralPer;
       this.imFotoPer = imFotoPer;
       this.dePotoPer = dePotoPer;
       this.esPersona = esPersona;
       this.coInstruccion = coInstruccion;
       this.feModifica = feModifica;
       this.vaDiscapacidadPer = vaDiscapacidadPer;
       this.vaExtranjeroPer = vaExtranjeroPer;
       this.coPaisOrigenPer = coPaisOrigenPer;
       this.nbCiudadResidePer = nbCiudadResidePer;
       this.feResidePer = feResidePer;
       this.coCondicionMigratoriaPer = coCondicionMigratoriaPer;
       this.nuCargaFamiliarPer = nuCargaFamiliarPer;
       this.vaPoseeLincenciaPer = vaPoseeLincenciaPer;
       this.nuPorcentajeDiscapacidadPer = nuPorcentajeDiscapacidadPer;
       this.vaDisponibilidadParaViajarPer = vaDisponibilidadParaViajarPer;
       this.deCantonPer = deCantonPer;
       this.nuCarnetConadisPer = nuCarnetConadisPer;
       this.beCurriculos = beCurriculos;
       this.beEmpresas = beEmpresas;
    }
   
    public Integer getCoPersona() {
        return this.coPersona;
    }
    
    public void setCoPersona(Integer coPersona) {
        this.coPersona = coPersona;
    }
    public BeCatalogo getBeCatalogoByCoAreaEstudios() {
        return this.beCatalogoByCoAreaEstudios;
    }
    
    public void setBeCatalogoByCoAreaEstudios(BeCatalogo beCatalogoByCoAreaEstudios) {
        this.beCatalogoByCoAreaEstudios = beCatalogoByCoAreaEstudios;
    }
    public BeCatalogo getBeCatalogoByCoEstadoCivilPer() {
        return this.beCatalogoByCoEstadoCivilPer;
    }
    
    public void setBeCatalogoByCoEstadoCivilPer(BeCatalogo beCatalogoByCoEstadoCivilPer) {
        this.beCatalogoByCoEstadoCivilPer = beCatalogoByCoEstadoCivilPer;
    }
    public BeCatalogo getBeCatalogoByCoTipoIdentificacionPer() {
        return this.beCatalogoByCoTipoIdentificacionPer;
    }
    
    public void setBeCatalogoByCoTipoIdentificacionPer(BeCatalogo beCatalogoByCoTipoIdentificacionPer) {
        this.beCatalogoByCoTipoIdentificacionPer = beCatalogoByCoTipoIdentificacionPer;
    }
    public BeCatalogo getBeCatalogoByCoGeneroPer() {
        return this.beCatalogoByCoGeneroPer;
    }
    
    public void setBeCatalogoByCoGeneroPer(BeCatalogo beCatalogoByCoGeneroPer) {
        this.beCatalogoByCoGeneroPer = beCatalogoByCoGeneroPer;
    }
    public AdUsuario getAdUsuario() {
        return this.adUsuario;
    }
    
    public void setAdUsuario(AdUsuario adUsuario) {
        this.adUsuario = adUsuario;
    }
    public BeCatalogo getBeCatalogoByCoPaisResidePer() {
        return this.beCatalogoByCoPaisResidePer;
    }
    
    public void setBeCatalogoByCoPaisResidePer(BeCatalogo beCatalogoByCoPaisResidePer) {
        this.beCatalogoByCoPaisResidePer = beCatalogoByCoPaisResidePer;
    }
    public BeCatalogo getBeCatalogoByCoTipoLicenciaPer() {
        return this.beCatalogoByCoTipoLicenciaPer;
    }
    
    public void setBeCatalogoByCoTipoLicenciaPer(BeCatalogo beCatalogoByCoTipoLicenciaPer) {
        this.beCatalogoByCoTipoLicenciaPer = beCatalogoByCoTipoLicenciaPer;
    }
    public BeCatalogo getBeCatalogoByCoTipoDiscapacidad() {
        return this.beCatalogoByCoTipoDiscapacidad;
    }
    
    public void setBeCatalogoByCoTipoDiscapacidad(BeCatalogo beCatalogoByCoTipoDiscapacidad) {
        this.beCatalogoByCoTipoDiscapacidad = beCatalogoByCoTipoDiscapacidad;
    }
    public BeCatalogo getBeCatalogoByCoProvinciaPer() {
        return this.beCatalogoByCoProvinciaPer;
    }
    
    public void setBeCatalogoByCoProvinciaPer(BeCatalogo beCatalogoByCoProvinciaPer) {
        this.beCatalogoByCoProvinciaPer = beCatalogoByCoProvinciaPer;
    }
    public BeCatalogo getBeCatalogoByCoGrupoEtnicoPer() {
        return this.beCatalogoByCoGrupoEtnicoPer;
    }
    
    public void setBeCatalogoByCoGrupoEtnicoPer(BeCatalogo beCatalogoByCoGrupoEtnicoPer) {
        this.beCatalogoByCoGrupoEtnicoPer = beCatalogoByCoGrupoEtnicoPer;
    }
    public BeCatalogo getBeCatalogoByCoNivelEstudios() {
        return this.beCatalogoByCoNivelEstudios;
    }
    
    public void setBeCatalogoByCoNivelEstudios(BeCatalogo beCatalogoByCoNivelEstudios) {
        this.beCatalogoByCoNivelEstudios = beCatalogoByCoNivelEstudios;
    }
    public String getNbPersona() {
        return this.nbPersona;
    }
    
    public void setNbPersona(String nbPersona) {
        this.nbPersona = nbPersona;
    }
    public String getApPersona() {
        return this.apPersona;
    }
    
    public void setApPersona(String apPersona) {
        this.apPersona = apPersona;
    }
    public String getNuIdentificaciobPer() {
        return this.nuIdentificaciobPer;
    }
    
    public void setNuIdentificaciobPer(String nuIdentificaciobPer) {
        this.nuIdentificaciobPer = nuIdentificaciobPer;
    }
    public String getDeDomicilioPer() {
        return this.deDomicilioPer;
    }
    
    public void setDeDomicilioPer(String deDomicilioPer) {
        this.deDomicilioPer = deDomicilioPer;
    }
    public Integer getCoCantonPer() {
        return this.coCantonPer;
    }
    
    public void setCoCantonPer(Integer coCantonPer) {
        this.coCantonPer = coCantonPer;
    }
    public Integer getCoSectorPer() {
        return this.coSectorPer;
    }
    
    public void setCoSectorPer(Integer coSectorPer) {
        this.coSectorPer = coSectorPer;
    }
    public String getDeBarrioPer() {
        return this.deBarrioPer;
    }
    
    public void setDeBarrioPer(String deBarrioPer) {
        this.deBarrioPer = deBarrioPer;
    }
    public String getNuTelefonoPer() {
        return this.nuTelefonoPer;
    }
    
    public void setNuTelefonoPer(String nuTelefonoPer) {
        this.nuTelefonoPer = nuTelefonoPer;
    }
    public String getNuCelularFono() {
        return this.nuCelularFono;
    }
    
    public void setNuCelularFono(String nuCelularFono) {
        this.nuCelularFono = nuCelularFono;
    }
    public Date getFeNacimientoPer() {
        return this.feNacimientoPer;
    }
    
    public void setFeNacimientoPer(Date feNacimientoPer) {
        this.feNacimientoPer = feNacimientoPer;
    }
    public String getDeLugarNacimientoPer() {
        return this.deLugarNacimientoPer;
    }
    
    public void setDeLugarNacimientoPer(String deLugarNacimientoPer) {
        this.deLugarNacimientoPer = deLugarNacimientoPer;
    }
    public String getDeNacionalidadPer() {
        return this.deNacionalidadPer;
    }
    
    public void setDeNacionalidadPer(String deNacionalidadPer) {
        this.deNacionalidadPer = deNacionalidadPer;
    }
    public String getDeEmailPer() {
        return this.deEmailPer;
    }
    
    public void setDeEmailPer(String deEmailPer) {
        this.deEmailPer = deEmailPer;
    }
    public Integer getCoNivelAcademicoPer() {
        return this.coNivelAcademicoPer;
    }
    
    public void setCoNivelAcademicoPer(Integer coNivelAcademicoPer) {
        this.coNivelAcademicoPer = coNivelAcademicoPer;
    }
    public Integer getNuAnioAprobadosPer() {
        return this.nuAnioAprobadosPer;
    }
    
    public void setNuAnioAprobadosPer(Integer nuAnioAprobadosPer) {
        this.nuAnioAprobadosPer = nuAnioAprobadosPer;
    }
    public String getDeTituProfesionPer() {
        return this.deTituProfesionPer;
    }
    
    public void setDeTituProfesionPer(String deTituProfesionPer) {
        this.deTituProfesionPer = deTituProfesionPer;
    }
    public String getCoSituLaboralPer() {
        return this.coSituLaboralPer;
    }
    
    public void setCoSituLaboralPer(String coSituLaboralPer) {
        this.coSituLaboralPer = coSituLaboralPer;
    }
    public String getCoExpLaboralPer() {
        return this.coExpLaboralPer;
    }
    
    public void setCoExpLaboralPer(String coExpLaboralPer) {
        this.coExpLaboralPer = coExpLaboralPer;
    }
    public byte[] getImFotoPer() {
        return this.imFotoPer;
    }
    
    public void setImFotoPer(byte[] imFotoPer) {
        this.imFotoPer = imFotoPer;
    }
    public String getDePotoPer() {
        return this.dePotoPer;
    }
    
    public void setDePotoPer(String dePotoPer) {
        this.dePotoPer = dePotoPer;
    }
    public String getEsPersona() {
        return this.esPersona;
    }
    
    public void setEsPersona(String esPersona) {
        this.esPersona = esPersona;
    }
    public Integer getCoInstruccion() {
        return this.coInstruccion;
    }
    
    public void setCoInstruccion(Integer coInstruccion) {
        this.coInstruccion = coInstruccion;
    }
    public Date getFeModifica() {
        return this.feModifica;
    }
    
    public void setFeModifica(Date feModifica) {
        this.feModifica = feModifica;
    }
    public String getVaDiscapacidadPer() {
        return this.vaDiscapacidadPer;
    }
    
    public void setVaDiscapacidadPer(String vaDiscapacidadPer) {
        this.vaDiscapacidadPer = vaDiscapacidadPer;
    }
    public String getVaExtranjeroPer() {
        return this.vaExtranjeroPer;
    }
    
    public void setVaExtranjeroPer(String vaExtranjeroPer) {
        this.vaExtranjeroPer = vaExtranjeroPer;
    }
    public Integer getCoPaisOrigenPer() {
        return this.coPaisOrigenPer;
    }
    
    public void setCoPaisOrigenPer(Integer coPaisOrigenPer) {
        this.coPaisOrigenPer = coPaisOrigenPer;
    }
    public String getNbCiudadResidePer() {
        return this.nbCiudadResidePer;
    }
    
    public void setNbCiudadResidePer(String nbCiudadResidePer) {
        this.nbCiudadResidePer = nbCiudadResidePer;
    }
    public Date getFeResidePer() {
        return this.feResidePer;
    }
    
    public void setFeResidePer(Date feResidePer) {
        this.feResidePer = feResidePer;
    }
    public Integer getCoCondicionMigratoriaPer() {
        return this.coCondicionMigratoriaPer;
    }
    
    public void setCoCondicionMigratoriaPer(Integer coCondicionMigratoriaPer) {
        this.coCondicionMigratoriaPer = coCondicionMigratoriaPer;
    }
    public Integer getNuCargaFamiliarPer() {
        return this.nuCargaFamiliarPer;
    }
    
    public void setNuCargaFamiliarPer(Integer nuCargaFamiliarPer) {
        this.nuCargaFamiliarPer = nuCargaFamiliarPer;
    }
    public String getVaPoseeLincenciaPer() {
        return this.vaPoseeLincenciaPer;
    }
    
    public void setVaPoseeLincenciaPer(String vaPoseeLincenciaPer) {
        this.vaPoseeLincenciaPer = vaPoseeLincenciaPer;
    }
    public String getNuPorcentajeDiscapacidadPer() {
        return this.nuPorcentajeDiscapacidadPer;
    }
    
    public void setNuPorcentajeDiscapacidadPer(String nuPorcentajeDiscapacidadPer) {
        this.nuPorcentajeDiscapacidadPer = nuPorcentajeDiscapacidadPer;
    }
    public String getVaDisponibilidadParaViajarPer() {
        return this.vaDisponibilidadParaViajarPer;
    }
    
    public void setVaDisponibilidadParaViajarPer(String vaDisponibilidadParaViajarPer) {
        this.vaDisponibilidadParaViajarPer = vaDisponibilidadParaViajarPer;
    }
    public String getDeCantonPer() {
        return this.deCantonPer;
    }
    
    public void setDeCantonPer(String deCantonPer) {
        this.deCantonPer = deCantonPer;
    }
    public String getNuCarnetConadisPer() {
        return this.nuCarnetConadisPer;
    }
    
    public void setNuCarnetConadisPer(String nuCarnetConadisPer) {
        this.nuCarnetConadisPer = nuCarnetConadisPer;
    }
    public Set getBeCurriculos() {
        return this.beCurriculos;
    }
    
    public void setBeCurriculos(Set beCurriculos) {
        this.beCurriculos = beCurriculos;
    }
    public Set getBeEmpresas() {
        return this.beEmpresas;
    }
    
    public void setBeEmpresas(Set beEmpresas) {
        this.beEmpresas = beEmpresas;
    }




}


