package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA



/**
 * BeRefePersonal generated by hbm2java
 */
public class BeRefePersonal  implements java.io.Serializable {


     private Integer coRefePersonal;
     private BeCurriculo beCurriculo;
     private String nbRefePersonal;
     private String nbCargoRefePersonal;
     private String nuTelefonoRefePersonal;
     private String esEstado;
     private String vaTipoRelacion;
     private String vaDireccion;

    public BeRefePersonal() {
    }

	
    public BeRefePersonal(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BeRefePersonal(BeCurriculo beCurriculo, String nbRefePersonal, String nbCargoRefePersonal, String nuTelefonoRefePersonal, String esEstado, String vaTipoRelacion, String vaDireccion) {
       this.beCurriculo = beCurriculo;
       this.nbRefePersonal = nbRefePersonal;
       this.nbCargoRefePersonal = nbCargoRefePersonal;
       this.nuTelefonoRefePersonal = nuTelefonoRefePersonal;
       this.esEstado = esEstado;
       this.vaTipoRelacion = vaTipoRelacion;
       this.vaDireccion = vaDireccion;
    }
   
    public Integer getCoRefePersonal() {
        return this.coRefePersonal;
    }
    
    public void setCoRefePersonal(Integer coRefePersonal) {
        this.coRefePersonal = coRefePersonal;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public String getNbRefePersonal() {
        return this.nbRefePersonal;
    }
    
    public void setNbRefePersonal(String nbRefePersonal) {
        this.nbRefePersonal = nbRefePersonal;
    }
    public String getNbCargoRefePersonal() {
        return this.nbCargoRefePersonal;
    }
    
    public void setNbCargoRefePersonal(String nbCargoRefePersonal) {
        this.nbCargoRefePersonal = nbCargoRefePersonal;
    }
    public String getNuTelefonoRefePersonal() {
        return this.nuTelefonoRefePersonal;
    }
    
    public void setNuTelefonoRefePersonal(String nuTelefonoRefePersonal) {
        this.nuTelefonoRefePersonal = nuTelefonoRefePersonal;
    }
    public String getEsEstado() {
        return this.esEstado;
    }
    
    public void setEsEstado(String esEstado) {
        this.esEstado = esEstado;
    }
    public String getVaTipoRelacion() {
        return this.vaTipoRelacion;
    }
    
    public void setVaTipoRelacion(String vaTipoRelacion) {
        this.vaTipoRelacion = vaTipoRelacion;
    }
    public String getVaDireccion() {
        return this.vaDireccion;
    }
    
    public void setVaDireccion(String vaDireccion) {
        this.vaDireccion = vaDireccion;
    }




}


