package ec.gob.celec.persistencia;
// Generated 17/06/2014 12:52:51 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * BeSelecionCvOfer generated by hbm2java
 */
public class BeSelecionCvOfer  implements java.io.Serializable {


     private Integer coSeleccionCvOfer;
     private BeOfertaEmpleo beOfertaEmpleo;
     private BeCurriculo beCurriculo;
     private BigDecimal vaCalificacionSeleccionCv;
     private String esSeleccionCvOfer;
     private String deProcesadoxSeleccionCv;
     private Set beEvaluacionCvs = new HashSet(0);

    public BeSelecionCvOfer() {
    }

	
    public BeSelecionCvOfer(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public BeSelecionCvOfer(BeOfertaEmpleo beOfertaEmpleo, BeCurriculo beCurriculo, BigDecimal vaCalificacionSeleccionCv, String esSeleccionCvOfer, String deProcesadoxSeleccionCv, Set beEvaluacionCvs) {
       this.beOfertaEmpleo = beOfertaEmpleo;
       this.beCurriculo = beCurriculo;
       this.vaCalificacionSeleccionCv = vaCalificacionSeleccionCv;
       this.esSeleccionCvOfer = esSeleccionCvOfer;
       this.deProcesadoxSeleccionCv = deProcesadoxSeleccionCv;
       this.beEvaluacionCvs = beEvaluacionCvs;
    }
   
    public Integer getCoSeleccionCvOfer() {
        return this.coSeleccionCvOfer;
    }
    
    public void setCoSeleccionCvOfer(Integer coSeleccionCvOfer) {
        this.coSeleccionCvOfer = coSeleccionCvOfer;
    }
    public BeOfertaEmpleo getBeOfertaEmpleo() {
        return this.beOfertaEmpleo;
    }
    
    public void setBeOfertaEmpleo(BeOfertaEmpleo beOfertaEmpleo) {
        this.beOfertaEmpleo = beOfertaEmpleo;
    }
    public BeCurriculo getBeCurriculo() {
        return this.beCurriculo;
    }
    
    public void setBeCurriculo(BeCurriculo beCurriculo) {
        this.beCurriculo = beCurriculo;
    }
    public BigDecimal getVaCalificacionSeleccionCv() {
        return this.vaCalificacionSeleccionCv;
    }
    
    public void setVaCalificacionSeleccionCv(BigDecimal vaCalificacionSeleccionCv) {
        this.vaCalificacionSeleccionCv = vaCalificacionSeleccionCv;
    }
    public String getEsSeleccionCvOfer() {
        return this.esSeleccionCvOfer;
    }
    
    public void setEsSeleccionCvOfer(String esSeleccionCvOfer) {
        this.esSeleccionCvOfer = esSeleccionCvOfer;
    }
    public String getDeProcesadoxSeleccionCv() {
        return this.deProcesadoxSeleccionCv;
    }
    
    public void setDeProcesadoxSeleccionCv(String deProcesadoxSeleccionCv) {
        this.deProcesadoxSeleccionCv = deProcesadoxSeleccionCv;
    }
    public Set getBeEvaluacionCvs() {
        return this.beEvaluacionCvs;
    }
    
    public void setBeEvaluacionCvs(Set beEvaluacionCvs) {
        this.beEvaluacionCvs = beEvaluacionCvs;
    }




}


